### ISSUE TITLE
Is it possible to plot multiple lines using free account?

### ISSUE THREAD

**Issue by thekenu** [seriesci/support#2]
I've been trying to use 
```
URL:.../many
Data:

{
    "sha": "c28cf6f76e5b562032510cc74c1a2f7225b75085",
    "values": [
        {"line": "first", "value": "8.9 %"},
        {"line": "second", "value": "3.9 %"},
        {"line": "third", "value": "4.5 %"},
    ]
}
```

to plot multiple lines, but I just can't seem to get it working. Every time I try to plot multiple lines, the SeriesCI page just stops loading altogether (`https://seriesci.com/{user}/{repo}/tree/{branch_name}`).  I have no problem using `URL.../one` or `URL.../many` but with only one line.

**Comment by zemirco** [comment]
Hey thekenu,

yes, it should be possible. Did you get any error message from your POST request or did it simply say "ok" with status 200?

Here you can see a public demo repo from me that uses multiple lines https://github.com/seriesci/demo-many-go

Could you create a public demo repository and start sending some values to seriesci? I will have a look at the logs if I can find anything unusual.

**Comment by thekenu** [comment]
Resolved with @zemirco via email!
