### ISSUE TITLE
Ordering of values got messed up

### ISSUE THREAD

**Issue by thekenu** [seriesci/support#3]
Not sure when it started but at some point the order of my values became messed up. [All the newest ](https://seriesci.com/UBCFormulaElectric/Consolidated-Firmware/series/master/PDM)values for each series get placed at the very bottom:
![image](https://user-images.githubusercontent.com/16970019/80428546-f54e9680-889e-11ea-96b9-49a703a1cb06.png)

This also messed up the plotting:
![image](https://user-images.githubusercontent.com/16970019/80428629-262ecb80-889f-11ea-8f8f-d139851eef12.png)

**Comment by zemirco** [comment]
Hey thekenu,

you're right. I can see your problem and will look into this. I'll let you know as soon as I have more information.

Best regards,
Mirco

**Comment by zemirco** [comment]
Good morning from Germany,

we have identified the issue and are currently working on a fix. The data is fine it's just a problem with our visualisation.

Best regards,
Mirco

**Comment by thekenu** [comment]
Awesome, looking forward to the fix!

**Comment by zemirco** [comment]
We have deployed some fixes. It should look better now. We're not done yet and there are still some minor glitches. We'll let you know when we're done.

**Comment by zemirco** [comment]
We're done. Everything should be fine now.

Thank you for opening this issue and let us know if you have more 😄
