### ISSUE TITLE
Is there a way to view all data at once?

### ISSUE THREAD

**Issue by thekenu** [seriesci/support#4]
It looks like each series only plots the most recent ~25 or so data entries.
![image](https://user-images.githubusercontent.com/16970019/80931084-81affc00-8d6c-11ea-98a2-ed136cf16163.png)

Is there some way to view older data? And is there also a way to download all the past data at once so I can analyze it offline?

**Comment by zemirco** [comment]
Hey thekenu,

two really good questions.

1. At the moment you can only see the 30 latest commits. This is due to the GitHub API that returns pages of 30 items. I will add a button to load more pages. That way you can see more data.

2. Good idea! I'll add a feature to download the data as .csv and .json.

Best regards,
Mirco

**Comment by zemirco** [comment]
Hey,

good news 🥳 

<img width="1178" alt="Screenshot 2020-05-05 at 20 47 40" src="https://user-images.githubusercontent.com/1132354/81103783-d771d900-8f11-11ea-9404-496167323fce.png">

You can now load more values when you click on the brand new "Load more" button on the series page https://seriesci.com/UBCFormulaElectric/Consolidated-Firmware/series/master/PDM

Now working on the data export.

**Comment by zemirco** [comment]
And more good news.

You can now download all values from a single series.

<img width="1136" alt="Screenshot 2020-05-05 at 22 43 50" src="https://user-images.githubusercontent.com/1132354/81114263-fe380b80-8f21-11ea-8a62-eb1ee4bae8a9.png">

Find the link at Series > Settings.

**Comment by thekenu** [comment]
Thank you! Is there a way to embed the branch name in the CSV file as well? I would like to just focus on one branch at a time (i.e. master branch)

**Comment by zemirco** [comment]
Hey thekenu,

I'm always impressed by your great feedback. Please keep it coming 👍

I've added another download button to each series. The resulting CSV file contains all the data that you see in the table right below the button, including the branch name.

Have fun analysing the data offline. Out of interest, what do you want to do with it?

Best regards,
Mirco

**Comment by zemirco** [comment]
Here is a little sneak peek

![Screenshot 2020-05-06 at 16 39 17](https://user-images.githubusercontent.com/1132354/81190497-338f3880-8fb8-11ea-91fb-11bbb560a751.png)

Enojy!

**Comment by thekenu** [comment]
It works great, thanks! Honestly I don't have a specific use-case for offline data at the moment. I was just hoping to take ownership of the raw data for my own record! :smile:
