### ISSUE TITLE
Issue with whitespaces in series name

### ISSUE THREAD

**Issue by kopach** [seriesci/support#5]
I've posted series with white space like so: `https://seriesci.com/api/repos/kopach/karma-sabarivka-reporter/lines%20of%20code/combined` and now I neither can use nor even remove that from the dashboard - server returns 500 status code.
Any chance I can

1. remove those series from dashboard? if yes, how?
2. use series with white spaces in it?

**Comment by zemirco** [comment]
Hey @kopach 

good question. Let me have a look into this problem. I'll get back to you when I've got some more information.

For `lines of code` I usually use `loc`. It's shorter and valid inside a URL. Whitespace in URLs are often tricky.

Best regards,
Mirco

**Comment by kopach** [comment]
Hey @zemirco 
Thanks for fast response. Yes, `loc` is also fine with me in context of URL. But, for dashboard web view I would really prefer something more meaningful and clear for everyone. That's why I've tried with whitespaces in URL. Personally I would really prefer having spaces in widget names on dashboard. Maybe, that could be achieved by introducing another `name` property or so? What do you think?

**Comment by zemirco** [comment]
That's a really good point. Maybe I have a solution for you.

You're able to add a **description** to every series.

1. Click on the tab **Series**. Then click on **Settings** on the right side.

![Screenshot 2020-06-24 at 15 13 18](https://user-images.githubusercontent.com/1132354/85563355-96eb2d80-b62d-11ea-9453-ebe4a425db62.png)
2. Enter some description to your series to make it more meaningful

![Screenshot 2020-06-24 at 15 13 29](https://user-images.githubusercontent.com/1132354/85563363-98b4f100-b62d-11ea-8647-93b4076471dc.png)

3. The description shows up on the dashboard.

![Screenshot 2020-06-24 at 15 13 38](https://user-images.githubusercontent.com/1132354/85563359-9783c400-b62d-11ea-9d44-6a9c50ee33b0.png)

Does it help?

I tried to keep the app as close to the GitHub application as possible. Your username should not contain whitespace and also your repository cannot contain whitespace. That's where my decision is coming from. However using an extra field for the name and another one for the URL might also make sense.

Best regards,
Mirco

**Comment by kopach** [comment]
I think, description might work for me. Thanks. And if you find a way I can remove already existing series with whitespaces - please let me know. Thanks.

**Comment by zemirco** [comment]
I've deployed a fix and it should work now. Could you please try?

https://seriesci.com/kopach/karma-sabarivka-reporter/series

Let me know if it works for you!

**Comment by kopach** [comment]
Yes, works now. Thank you
