### ISSUE TITLE
Expired certificate on main page

### ISSUE THREAD

**Issue by boscard** [seriesci/support#8]
Hi, 
Seems that https://seriesci.com/ is using expired certificate, so page can't be displayed and also there is issue with sending data using curl.

**Comment by zemirco** [comment]
Hey,

thank you so much 🥰

I fixed it and everything should work as expected.

Best regards,
Mirco

**Comment by douglasduteil** [comment]
🆙 @zemirco 

![image](https://user-images.githubusercontent.com/730511/115160883-cbd3df80-a09a-11eb-9a14-d13e220dfce5.png)
